### ISSUE TITLE
Duplicate functions: D3bot_UpdatePathProgress D3bot_UpdatePath

### ISSUE THREAD

**Issue by Antizombie** [Dadido3/D3bot#112]
Duplicate functions:
D3bot_UpdatePathProgress
D3bot_UpdatePath

They have similar but different code, I don't know which ones are "needed."

![изображение](https://github.com/Dadido3/D3bot/assets/739505/4f9dd25e-2951-42ba-8e71-75ec44195708)

**Comment by Dadido3** [comment]
This was added here: https://github.com/Dadido3/D3bot/pull/85.
Some functions needed to be duplicated in order to have variants that work with source navmeshes (.nav files).

If you don't care about `.nav` compatibility you can forget about everything below:
https://github.com/Dadido3/D3bot/blob/5c5135f98ff49799e22c37d79103aadb2e846789/lua/d3bot/sv_extend_player.lua#L368

There are some other files which use the same method to override some functions in case a source navmesh is used.

**Comment by Antizombie** [comment]
Thanks, I thought it was a bug.
I didn't notice D3bot.UsingSourceNav )))))
