### ISSUE TITLE
No Zombie in Objective Maps

### ISSUE THREAD

**Issue by LeoABELS121** [Dadido3/D3bot#132]
Hello,
Zombie bots appear well on zombie survival maps. However, they do not appear on the objective maps. I'm using d3bot version 1.2.0.

**Comment by Dadido3** [comment]
Have you followed the [installation instructions](https://github.com/Dadido3/D3bot?tab=readme-ov-file#installation)? You have to copy the navmeshes from the addon into another directory. Otherwise D3bot will fall back to "Source" navmeshes, which not all maps have, and which are not 100% compatible with how the bot works.

Otherwise i need more information.

**Comment by LeoABELS121** [comment]
It's corrected. Ulx and Ulib were not up to date.

**Comment by Dadido3** [comment]
Thanks for the reply. Gonna close this issue then.
