### ISSUE TITLE
Bots getting stuck while trying to attack a deployable

### ISSUE THREAD

**Issue by HordeRally** [Dadido3/D3bot#60]
If the bots can target deployables then some stupid stuff can happen.

For example, on gm_construct, if you cade in the secret room and place a turret on the wall, the bots would go to the room above that and try to attack it. Easiest fix is to just make them target nothing.

**Comment by CWorm** [comment]
This is because bots see all entities the same - they will assume the entity is on the nearest area when this isn't even the case (ie. standing on a shelf in a room will make bots think you're on the roof), currently the fix options are: 

A) Remove the entity from target list.
B) Change navmesh to include a zone in the same room, exactly same as the floor but relocate it to be on the ceiling - this will make so even if something is on the ceiling, it will still use the navmesh in the room rather one on the roof.
C) Change navmesh so that the zone is in the middle height of the room, and raise the navmesh above the room as well.

**Comment by HordeRally** [comment]
Thanks!
