### ISSUE TITLE
Spawn

### ISSUE THREAD

**Issue by SamWall1337** [Dadido3/D3bot#62]
What to do to make bots spawn where they are closer to the player, and not away from the players. (By clicking on R, spavnyas away from the players)

**Comment by CWorm** [comment]
That seems more like an issue regarding Zombie Survival and not the bots themselves. 

You'd have to code it yourself in order to check (for bots) which spawn/nest is the nearest to humans, and use that one, probably good idea being to give some offset to prevent one player forcing all zombies to spawn there.
